workflows:
  ios-native-quick-start:
    name: iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        BUNDLE_ID: "io.codemagic.sample.iosnative"
        XCODE_WORKSPACE: "CodemagicSample.xcworkspace"
        XCODE_SCHEME: "CodemagicSample"
        APP_ID: 1555555551
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: | 
          pod install
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles  
      - name: build
        script: | 
          xcodebuild build -workspace project.xcworkspace -scheme project
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
